import sharp from 'sharp'
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const SRC_DIR = path.join(ROOT, 'assets-original')
const OUT_DIR = path.join(ROOT, 'public', 'images')
const MANIFEST = path.join(ROOT, 'src', 'data', 'images.js')

// Slug comes from the filename: "Modern Tech Solution.png" -> "modern-tech-solution".
// Add a file to assets-original/ and it is picked up automatically.
function slugify(file) {
  return path
    .basename(file, path.extname(file))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

const IMAGE_EXT = /\.(png|jpe?g|webp)$/i

// Portrait sources are displayed much larger, so they get a third variant.
function targetsFor(meta) {
  return meta.width / meta.height < 1
    ? { widths: [400, 800, 1200], quality: 82 }
    : { widths: [400, 800], quality: 80 }
}

const before = { webp: 0, jpg: 0 }

async function processImage(file) {
  const slug = slugify(file)
  const input = path.join(SRC_DIR, file)

  const meta = await sharp(input).metadata()
  const { widths, quality } = targetsFor(meta)
  const capped = widths.filter((w) => w < meta.width)
  const finalWidths = capped.length ? capped : [Math.min(meta.width, widths.at(-1))]

  for (const width of finalWidths) {
    const pipeline = sharp(input).resize({ width, withoutEnlargement: true })

    const webp = await pipeline
      .clone()
      .webp({ quality })
      .toBuffer()
    const jpg = await pipeline.clone().jpeg({ quality, mozjpeg: true }).toBuffer()

    before.webp += webp.length
    before.jpg += jpg.length

    await sharp(webp).toFile(path.join(OUT_DIR, `${slug}-${width}.webp`))
    await sharp(jpg).toFile(path.join(OUT_DIR, `${slug}-${width}.jpg`))
  }

  console.log(
    `  ${slug.padEnd(14)} ${meta.width}x${meta.height} -> widths [${finalWidths.join(', ')}]`,
  )
  return { base: `/images/${slug}`, widths: finalWidths, original: `${meta.width}x${meta.height}` }
}

async function main() {
  if (!existsSync(SRC_DIR)) {
    console.error('No assets-original/ directory found.')
    process.exit(1)
  }

  await mkdir(OUT_DIR, { recursive: true })

  const files = (await readdir(SRC_DIR)).filter((f) => IMAGE_EXT.test(f))

  if (!files.length) {
    console.error('No source images matched in assets-original/.')
    process.exit(1)
  }

  console.log(`Optimizing ${files.length} images from assets-original/\n`)

  const entries = {}
  for (const file of files) {
    entries[slugify(file)] = await processImage(file)
  }

  await writeFile(
    MANIFEST,
    `// Generated by scripts/optimize-images.mjs - do not edit by hand.
// Run "npm run images" after replacing a source file in assets-original/.
export const images = ${JSON.stringify(entries, null, 2)}
`,
  )

  const sourceBytes = (
    await Promise.all(files.map((f) => stat(path.join(SRC_DIR, f))))
  ).reduce((total, entry) => total + entry.size, 0)

  console.log(
    `\nSource: ${(sourceBytes / 1024 / 1024).toFixed(2)} MB` +
      `\nWebP total: ${(before.webp / 1024).toFixed(0)} KB` +
      `\nJPEG fallback total: ${(before.jpg / 1024).toFixed(0)} KB` +
      `\nCombined: ${((before.webp + before.jpg) / 1024).toFixed(0)} KB`,
  )
  console.log('Wrote public/images/ and src/data/images.js')
}

main()